#include <iostream>
#include <vector>
#include <chrono>

using namespace std::literals::chrono_literals;

#include "test_data.h"
#include "lcs.h"

void test_lcs()
{
    int right { 0 };
    int wrong { 0 };
    std::vector<int> vo(256);
    auto start = std::chrono::high_resolution_clock::now();
#if 0
    for (int n = 1; n < 139; n += 2)
    {
        std::cout << "std::fill(vo.begin(), vo.end(), -1);\n";
        std::cout << "std::cout << \"std::fill(vo.begin(), vo.end(), -1);\\n\";\n";
        std::cout << "std::cout << \"(lcs_e(a" << n << ", a" << n + 1 << ", vo) != \" << lcs_e(a" << n << ", a" << n + 1 << ", vo) << \") ? ++wrong : ++right;\\n\" ;\n";
    }
#else
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a1, a2, vo) != 1) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a3, a4, vo) != 1) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a5, a6, vo) != 3) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a7, a8, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a9, a10, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a11, a12, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a13, a14, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a15, a16, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a17, a18, vo) != 1) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a19, a20, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a21, a22, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a23, a24, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a25, a26, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a27, a28, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a29, a30, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a31, a32, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a33, a34, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a35, a36, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a37, a38, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a39, a40, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a41, a42, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a43, a44, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a45, a46, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a47, a48, vo) != 15) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a49, a50, vo) != 14) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a51, a52, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a53, a54, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a55, a56, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a57, a58, vo) != 3) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a59, a60, vo) != 4) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a61, a62, vo) != 4) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a63, a64, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a65, a66, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a67, a68, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a69, a70, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a71, a72, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a73, a74, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a75, a76, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a77, a78, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a79, a80, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a81, a82, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a83, a84, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a85, a86, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a87, a88, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a89, a90, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a91, a92, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a93, a94, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a95, a96, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a97, a98, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a99, a100, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a101, a102, vo) != 3) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a103, a104, vo) != 3) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a105, a106, vo) != 4) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a107, a108, vo) != 5) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a109, a110, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a111, a112, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a113, a114, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a115, a116, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a117, a118, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a119, a120, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a121, a122, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a123, a124, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a125, a126, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a127, a128, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a129, a130, vo) != 5) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a131, a132, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a133, a134, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a135, a136, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e(a137, a138, vo) != 9) ? ++wrong : ++right;
#endif    
    auto end = std::chrono::high_resolution_clock::now();
    std::cout << "test_lcs  :  " << (end - start) / 1us << "ms\n";
    std::cout << "right = " << right << ", wrong = " << wrong << "\n";
}

void test_lcs_brief()
{
    int right { 0 };
    int wrong { 0 };
    std::vector<int> vo(256);
    auto start = std::chrono::high_resolution_clock::now();
#if 0
    for (int n = 1; n < 139; n += 2)
    {
        std::cout << "std::fill(vo.begin(), vo.end(), -1);\n";
        std::cout << "std::cout << \"std::fill(vo.begin(), vo.end(), -1);\\n\";\n";
        std::cout << "std::cout << \"(lcs_e(a" << n << ", a" << n + 1 << ", vo) != \" << lcs_e(a" << n << ", a" << n + 1 << ", vo) << \") ? ++wrong : ++right;\\n\" ;\n";
    }
#else
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a1, a2, vo) != 1) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a3, a4, vo) != 1) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a5, a6, vo) != 3) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a7, a8, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a9, a10, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a11, a12, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a13, a14, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a15, a16, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a17, a18, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a19, a20, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a21, a22, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a23, a24, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a25, a26, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a27, a28, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a29, a30, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a31, a32, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a33, a34, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a35, a36, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a37, a38, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a39, a40, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a41, a42, vo) != 11) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a43, a44, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a45, a46, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a47, a48, vo) != 15) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a49, a50, vo) != 14) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a51, a52, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a53, a54, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a55, a56, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a57, a58, vo) != 3) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a59, a60, vo) != 4) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a61, a62, vo) != 4) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a63, a64, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a65, a66, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a67, a68, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a69, a70, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a71, a72, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a73, a74, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a75, a76, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a77, a78, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a79, a80, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a81, a82, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a83, a84, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a85, a86, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a87, a88, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a89, a90, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a91, a92, vo) != 12) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a93, a94, vo) != 10) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a95, a96, vo) != 9) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a97, a98, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a99, a100, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a101, a102, vo) != 3) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a103, a104, vo) != 3) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a105, a106, vo) != 4) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a107, a108, vo) != 5) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a109, a110, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a111, a112, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a113, a114, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a115, a116, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a117, a118, vo) != 8) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a119, a120, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a121, a122, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a123, a124, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a125, a126, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a127, a128, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a129, a130, vo) != 5) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a131, a132, vo) != 7) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a133, a134, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a135, a136, vo) != 6) ? ++wrong : ++right;
    std::fill(vo.begin(), vo.end(), -1);
    (lcs_e<v_brief_t>(a137, a138, vo) != 9) ? ++wrong : ++right;
#endif    
    auto end = std::chrono::high_resolution_clock::now();
    std::cout << "test_lcs_b :  " << (end - start) / 1us << "ms\n";
    std::cout << "right = " << right << ", wrong = " << wrong << "\n";
}